Update azure-pipelines-java.yml for Azure Pipelines

diff --git a/azure-pipelines-java.yml b/azure-pipelines-java.yml
--- a/azure-pipelines-java.yml
+++ b/azure-pipelines-java.yml
@@ -3,9 +3,7 @@ trigger:
 
 pool: agent1_pool
 
-variables:
-  TOMCAT_HOME: /opt/tomcat
-  WAR_NAME: JavaLoginShowcase.war
+   
 
 stages:
 # =========================
@@ -22,7 +20,6 @@ stages:
     - script: |
         echo "Current dir:"
         dir
-        mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout
         mvn clean package -DskipTests
       displayName: Maven Build
 
@@ -33,10 +30,11 @@ stages:
 
     - script: |
         echo "Searching for WAR..."
-        dir /s *.war
-      displayName: Find WAR
+        dir /s *.war || echo "WAR not found"
+        displayName: Find WAR
 
     - task: PublishBuildArtifacts@1
       inputs:
-        PathtoPublish: '**/*.war'
-        ArtifactName: drop
+        PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
+        ArtifactName: 'drop'
+        publishLocation: 'Container'
